# Generated by Django 5.1.6 on 2025-02-22 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalcondition',
            name='description',
        ),
    ]
